version: '3.9'

services:
  flask_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: team_R_app
    restart: always
    volumes:
      - ./src:/app/src  # Sync src directory for local development
    ports:
      - "42069:42069"
    environment:
      - FLASK_ENV=production
      - REDIS_HOST=redis
      - REDIS_PORT=6379
  
  # Redis cache
  redis:
    image: redis/redis-stack:latest
    container_name: team_R_cache
    restart: always
    ports:
      - "6379:6379"